In [1]:
import pandas
from pandas_datareader import data

In [10]:
df = pandas.read_csv('data/fundamental_trusted.csv')
df.head()

,PAPEL,COTACAO,P/L,P/VP,PSR,DIV_YIELD,P/ATIVO,P/CAP_GIRO,P/EBIT,P/ATIV_CIRC_LIQ,...,MRG_EBIT,MRG_LIQ,LIQ_CORR,ROIC,ROE,LIQ_2MESES,PATRIM_LIQ,DIV_BRUT/PATRIM,CRESC_REC_5A,SETOR
0,RRRP3,33.96,-7602.28,1.67,9.453,0.0000,1.262,3.21,27.67,4.79,...,0.3417,0.0220,4.79,0.0860,-0.0002,1.981650e+08,4.107890e+09,0.01,2.5632,Petroleo
1,CASH3,2.02,-338.85,2.27,7.791,0.0029,1.965,2.75,-178.61,3.10,...,-0.0436,-0.0115,21.09,-0.0363,-0.0067,1.144530e+08,7.138490e+08,0.00,0.0000,Serviços
2,GEPA4,28.90,-310.13,1.43,2.026,0.1017,688.000,-4.71,15.80,-1.66,...,0.1283,-0.0065,0.42,0.0534,-0.0046,1.889650e+04,1.907660e+09,0.68,-0.0057,Energia
3,GEPA3,28.00,-300.47,1.39,1.963,0.1050,667.000,-4.56,15.30,-1.61,...,0.1283,-0.0065,0.42,0.0534,-0.0046,6.217200e+03,1.907660e+09,0.68,-0.0057,Energia
4,FRTA3,4.66,-62.55,-0.15,552.000,0.0000,282.000,-0.12,-35.31,-0.10,...,-0.0156,-0.0088,0.06,-0.0096,0.0024,7.751850e+03,-6.475200e+07,-0.96,-0.2776,Agro

In [14]:
df_filtered = df[df['LIQ_2MESES'] > 1000000]

df_ranking = pandas.DataFrame()
df_ranking['IDX'] = range(0, 50)
df_ranking['EV/EBIT'] = df[df['EV/EBIT'] > 0].sort_values(by=['EV/EBIT'])['PAPEL'][:50].values
df_ranking['ROIC'] = df.sort_values(by=['ROIC'], ascending=False)['PAPEL'][:50].values

df_ranking.head()

   IDX EV/EBIT   ROIC
0    0   PSSA3  PSSA3
1    1   SULA4  AFLT3
2    2   WEST3  PLPL3
3    3   EVEN3  DMMO3
4    4   BRGE8  BLAU3

In [19]:
df_a = df_ranking.pivot_table(columns='EV/EBIT', values='IDX')
df_b = df_ranking.pivot_table(columns='ROIC', values='IDX')

# Merge dataframes
df_m = pandas.concat([df_a, df_b])

df_rank = df_m.dropna(axis=1).sum()
df_rank.sort_values()

PSSA3      0
PLPL3     10
AGRO3     22
WIZS3     26
PETR4     27
LVTC3     28
AFLT3     28
PETR3     29
CURY3     36
ALUP3     52
ALUP11    53
ALUP4     54
EQMA3B    54
LAVV3     57
JHSF3     58
TRPL4     72
EKTR4     73
CSRN3     75
CSRN5     77
EMAE4     85
REDE3     85
SLCE3     85
CEEB3     88
TRPL3     90
dtype: int64

In [28]:
stocks = df_rank.index.tolist()
df = pandas.DataFrame()
for i in stocks:
    df[i] = data.DataReader(name=f'{i}.SA', data_source='yahoo', start='2021-03-15')['Close']
    
df.to_csv('data/prices.csv', sep=',', header=True, index=True)